repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-xml
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: cargo-check
    -   id: clippy
    -   id: fmt
-   repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v6.3.0
    hooks:
    -   id: cspell
-   repo: https://github.com/redwarp/optimize-png-hooks
    rev: v1.1.0
    hooks:
    -   id: optimize-png
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.14
    hooks:
    -   id: mdformat
        additional_dependencies:
        -   mdformat-beautysh
        -   mdformat-black
        -   mdformat-config
        -   mdformat-gfm
        -   mdformat-rustfmt
        -   mdformat-tables
        -   mdformat-web
-   repo: https://github.com/sirosen/check-jsonschema
    rev: 0.17.1
    hooks:
    -   id: check-github-workflows
    -   id: check-github-actions
-   repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
    -   id: reuse

ci:
  skip:
  -   cargo-check
  -   clippy
  -   fmt
  -   check-github-actions
  -   check-github-workflows
